"""Remove Constraints

Revision ID: 3679acc4fa26
Revises: 0a2cfd7c5a45
Create Date: 2024-05-16 17:06:44.350403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3679acc4fa26'
down_revision = '0a2cfd7c5a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('mission_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('mission_start_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.alter_column('mission_start_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('mission_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
